/*TMODJS:{"version":1,"md5":"521f81a34f2cf1d237e7b827effc5f99"}*/
define(function(require) {
    return require("../../templates")("way/member/edit_form", function($data) {
        "use strict";
        var $utils = this, $escape = ($utils.$helpers, $utils.$escape), nickname = $data.nickname, memberrank = $data.memberrank, memberstatus = $data.memberstatus, cellphone = $data.cellphone, memberintegral = $data.memberintegral, accountid = $data.accountid, memberfrom = $data.memberfrom, activitycount = $data.activitycount, sex = $data.sex, mainbox = $data.mainbox, realname = $data.realname, addr = $data.addr, vdef7 = $data.vdef7, birthday = $data.birthday, followtime = $data.followtime, vdef3 = $data.vdef3, vdef5 = $data.vdef5, vdef6 = $data.vdef6, vdef4 = $data.vdef4, $out = "";
        return $out += ' <table cellpadding="0" cellspacing="0" border="0" width="90%" class="table auto mt-20 nohover">  <tr> <td width="20%">昵称:</td> <td width="80%"> <div> <input type="text" class="form-control col-xs-4" name="member.nickname" value="', 
        $out += $escape(nickname), $out += '" form_check="sys" ischeck="true" tip="此项为必填" wrong="此项为必填" re="(.+)" readonly="readonly" yes> <span class="fl red mt-5 ml-5 font-14">*</span> <span class="gray fl ml-5 mt-5">(<span class="red">*</span>号标记的为必填项)</span> </div> </td> </tr>  <tr> <td>级别:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(memberrank), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>状态:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += 1 == memberstatus ? "已关注" : "未关注", $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </td> </tr>  <tr> <td>手机号:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.cellphone" value="', 
        $out += $escape(cellphone), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="手机号格式不正确" re="((\\d{11}))" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>积分:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(memberintegral), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>账号名称:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(accountid), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>来源渠道:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(memberfrom), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>参加活动数:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(activitycount), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>性别:</td> <td class="tl"> <div radio_group="true" name="member.sex" form_check="sys" ischeck="false" script-role="check_wrap"> <input type="radio" value="1" name="member.sex" class="mr-5" ', 
        1 == sex && ($out += 'checked="checked"'), $out += '/> <span class="ml_10 mr-10">男</span> <input type="radio" value="2" name="member.sex" class="mr-5" ', 
        2 == sex && ($out += 'checked="checked"'), $out += '/> <span class="ml_10">女</span> </div> </td> </tr>  <tr> <td>邮箱:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.mainbox" form_check="sys" ischeck="free" tip="邮箱不能为空" wrong="邮箱格式不正确" re="(\\d{8}|\\d{11})|([0-9A-Za-z\\-_\\.]+)@([0-9a-z]+\\.[a-z]{2,3}(\\.[a-z]{2})?)" value="', 
        $out += $escape(mainbox), $out += '" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>真实姓名:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.realname" form_check="sys" ischeck="true" tip="真实姓名不能为空" wrong="真实姓名为20个字以内" re="(.{1,20})" value="', 
        $out += $escape(realname), $out += '" readonly="readonly" yes> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr>  <tr> <td>地址:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.addr" value="', 
        $out += $escape(addr), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="此项为必填" re="(.+)" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>备注:</td> <td class="tl"> <div> <textarea class="form-control col-xs-4" name="member.vdef7" form_check="sys" ischeck="free" tip="此项为必填" wrong="请填写100字以内的备注" re="((.|\\n){1,100})" readonly="readonly" yes>', 
        $out += $escape(vdef7), $out += '</textarea> </div> </td> </tr>  <tr> <td>出生日期:</td> <td script-role="check_wrap"> <div> <input type="text" class="form-control col-xs-4" name="member.birthday" value="', 
        $out += $escape(birthday), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="日期格式不正确" re="(\\d{4}\\-\\d{2}\\-\\d{2})" readonly="readonly" yes date> </div> </td> </tr>  <tr> <td>关注时间:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="" value="', 
        $out += $escape(followtime), $out += '" form_check="sys" ischeck="false" no_upload="false" readonly="readonly"> </div> </td> </tr>  <tr> <td>邮编:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.vdef3" value="', 
        $out += $escape(vdef3), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="邮编格式不正确" re="\\d{6}" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>身份证:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.vdef5" value="', 
        $out += $escape(vdef5), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="身份证格式不正确" re="((\\w{15})|(\\w{18}))" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>QQ:</td> <td> <div> <input type="text" class="form-control col-xs-4" name="member.vdef6" value="', 
        $out += $escape(vdef6), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="QQ号格式不正确" re="(\\d+)" readonly="readonly" yes> </div> </td> </tr>  <tr> <td>联系电话:</td> <td script-role="check_wrap"> <div> <input type="text" class="form-control col-xs-4" name="member.vdef4" value="', 
        $out += $escape(vdef4), $out += '" form_check="sys" ischeck="free" tip="此项为必填" wrong="电话格式不正确" re="((\\d{11})|(\\d{8})|(\\d{3}\\-\\d{8}))" readonly="readonly" yes> </div> </td> </tr> <tr> <td></td> <td class="tl"> <a modify-btn href="javascript:;" class="btn btn-danger pl-50 pr-50">修改</a> <a script-role="confirm-btn" href="javascript:;" class="btn btn-primary pl-50 pr-50">确定</a> </td> </tr> </table>', 
        new String($out);
    });
});