<link rel="stylesheet" href="<%=path %>statics/src/css/lib/reset.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/global.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/layer.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/bg.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/button.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/icon.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/form.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/size.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/table.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/box.css">
<link rel="stylesheet" href="<%=path %>statics/src/css/lib/wrong.css">