/*TMODJS:{"version":3,"md5":"4d3845f2b34ba0fa777032cd83757184"}*/
define(function(require) {
    return require("../templates")("upload_box/upload_box", function() {
        "use strict";
        var $utils = this, $helpers = $utils.$helpers, $string = $utils.$string, basePath = $helpers.basePath, $out = "";
        return $out += ' <div class="r-box upload-box none" data-ele="r-upload-box"> <div class="shadow"></div> <div class="content"> <div class="inner"> <div class="tab-head"> <ul class="clearfix"> <li class="r-btn tab-btn" widget-role="tab-head">本地上传</li> <li class="r-btn tab-btn" widget-role="tab-head">在线管理</li> <li class="r-btn tab-btn" widget-role="tab-head">图片搜索</li> </ul> </div> <div class="tab-content-wrap"> <div class="tab-content rel upload-wrap" widget-role="tab-content"> <div class="clearfix upload-wrap-inner">  <div class="fl local-wrap"> <div class="local overflow-h" cut-wrap> <div cut-area> <img src="', 
        $out += $string(basePath()), $out += '/lib/holder/blank.gif" data-ele="upload-view-img" class="upload_view_img"> </div> </div> <div class="tc mt-2 gray"> （请上传jpg,jpeg,gif,png格式且小于2M的图片） </div> <div class="upload-area"> <form action="" target="uploadframe" data-ele="upload-form" method="post" enctype="multipart/form-data"> <input type="file" name="upload" class="file" data-ele="upload-ele"> <input type="hidden" name="wminvalue" wmin> <input type="hidden" name="wmaxvalue" wmax> <input type="hidden" name="hminvalue" hmin> <input type="hidden" name="hmaxvalue" hmax>  <input type="hidden" name="isChangeType" isChangeType> <iframe class="none" frameborder="0" name="uploadframe"></iframe> </form> <div class="cover">点击选择图片</div> </div> </div>  <div class="fl right-view" right-view> </div> </div> <div class="btn-area"> <a class="btn btn-primary" data-ele="save-upload-btn" sc="confirm">确定</a> <a class="btn btn-danger" sc="close">取消</a> </div> </div> <div class="tab-content rel upload-wrap" widget-role="tab-content"> <div class="manage-outer"> <ul class="manage-wrap clearfix" manage-wrap> </ul> </div> <div class="tc mt-10 mb-10"> <a href="javascript:;" manage-more class="none">加载更多</a> </div> <div class="tc"> <a href="javascript:;" class="btn btn-primary" data-ele="save-manage-btn">确定</a> <a href="javascript:;" class="btn btn-danger" sc="close">取消</a> </div> </div> <div class="tab-content none" data-ele="baidu-search-wrap" widget-role="tab-content"> <div class="search-head clearfix ml-20 pt-20"> <input type="text" class="input-area fl mr-20" placeholder="请输入搜索关键词" data-ele="baidu-search-input"> <span class="fl gray mt-5 mr-5">宽</span> <input type="text" class="input-area fl mr-20 w_40" input-w value="100"> <span class="fl gray mt-5 mr-5">高</span> <input type="text" class="input-area fl mr-20 w_40" input-h value="100">  <button class="fl" data-ele="baidu-search-btn">百度一下</button> </div> <div class="seach-content mt-20"> <ul class="clearfix" data-ele="baidu-search-list">  </ul> </div> <div class="btn-area tc"> <a href="javascript:;" class="btn btn-primary" data-ele="save-baidu-btn">确定</a> <a href="javascript:;" class="btn btn-danger" sc="close">取消</a> </div> </div> </div> </div> </div> </div>', 
        new String($out);
    });
});