/*TMODJS:{"version":1,"md5":"5f5447808883e41df1a6d0fc0f071a2c"}*/
define(function(require) {
    return require("../../templates")("admin/user/form", function($data) {
        "use strict";
        var $utils = this, $escape = ($utils.$helpers, $utils.$escape), userName = $data.userName, userNote = $data.userNote, userCode = $data.userCode, userPassword = $data.userPassword, mails = $data.mails, ableTime = $data.ableTime, disableTime = $data.disableTime, $out = "";
        return $out += ' <table cellpadding="0" cellspacing="0" border="0" class="table auto nohover no mt-20" width="90%"> <tr> <td width="100">用户名称：</td> <td> <div> <input type="text" class="form-control col-xs-5" form_check="sys" ischeck="true" name="userinfo.userName" tip="此项为必填" wrong="请填写2-10位的用户名称" re="(.{2,10})" value="', 
        $out += $escape(userName), $out += '"> <span class="fl red mt-5 ml-5 font-14">*</span> <span class="gray fl ml-5 mt-5">(<span class="red">*</span>号标记的为必填项)</span> </div> </td> </tr> <tr> <td>用户描述：</td> <td> <div> <input type="text" class="form-control col-xs-5" form_check="sys" ischeck="true" name="userinfo.userNote" tip="此项为必填" wrong="用户描述不能超过20个字" re="(.{1,20})" value="', 
        $out += $escape(userNote), $out += '"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>用户账号：</td> <td> <div> <input type="text" class="form-control col-xs-5" form_check="sys" ischeck="true" name="userinfo.userCode" tip="此项为必填" wrong="用户账户为6-18位的数字，字母，_，并用字母开头" re="([a-zA-z](\\w|\\d|_){5,17})" value="', 
        $out += $escape(userCode), $out += '"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>用户密码：</td> <td> <div> <input type="password" class="form-control col-xs-5" name="userinfo.userPassword" form_check="sys" ischeck="true" tip="密码不能为空" wrong="请输入6-16位密码" re="(\\w{6,16})" sc="pass-new" value="', 
        $out += $escape(userPassword), $out += '"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>确认密码：</td> <td> <div> <input type="password" class="form-control col-xs-5" sc="re-new-pass" name="reNewPassWord" form_check="self" ischeck="true" tip="密码不能为空" wrong="两次输入的密码不一致" re="(\\w{6,16})" value="', 
        $out += $escape(userPassword), $out += '"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>邮箱：</td> <td> <div> <input type="text" class="form-control col-xs-5" name="userinfo.mails" form_check="sys" ischeck="true" tip="邮箱不能为空" wrong="邮箱格式不正确" re="(\\d{8}|\\d{11})|([0-9A-Za-z\\-_\\.]+)@([0-9a-z]+\\.[a-z]{2,3}(\\.[a-z]{2})?)" value="', 
        $out += $escape(mails), $out += '"> <span class="fl mt-8">（该邮箱用于找回密码）</span> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>生效日期：</td> <td script-role="check_wrap"> <div> <input type="text" class="form-control col-xs-5" form_check="sys" ischeck="true" name="userinfo.ableTime" tip="此项为必填" wrong="日期格式不正确" re="(\\d{4}\\-\\d{2}\\-\\d{2})" dateStart date value="', 
        $out += $escape(ableTime), $out += '" readonly="readonly"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td>失效日期：</td> <td script-role="check_wrap"> <div> <input type="text" class="form-control col-xs-5" form_check="sys" ischeck="true" name="userinfo.disableTime" tip="此项为必填" wrong="日期格式不正确" re="(\\d{4}\\-\\d{2}\\-\\d{2})" dateEnd date value="', 
        $out += $escape(disableTime), $out += '" readonly="readonly"> <span class="fl red mt-5 ml-5 font-14">*</span> </div> </td> </tr> <tr> <td></td> <td class="tl"> <a href="javascript:;" class="btn btn-primary pl-50 pr-50" script-role="confirm-btn">确定</a> </td> </tr> </table>', 
        new String($out);
    });
});